debug: true
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB
  security:
    user:
      name: wjp
      password: qwer
  data:
    rest:
      default-media-type: application/x-www-form-urlencoded
      base-path: /api
  mvc:
    log-request-details: true
    log-resolved-exception: true
    servlet:
      path: /

server:
  port: 8080