
debug: true
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB
  security:
    user:
      name: wjp
      password: qwer
      roles: USER
  data:
    rest:
      default-media-type: application/x-www-form-urlencoded
      base-path: /api
    jpa:
      repositories:
        # 如何对待Repo相关的bean,可以需要时才启动它
        bootstrap-mode: lazy
  mvc:
    log-request-details: true
    log-resolved-exception: true
    servlet:
      path: /
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://150.158.92.41:3306/loop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: loop
    password: qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
  main:
    banner-mode: console
server:
  port: 80

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
        web:
          server:
            adapter:
              HttpWebHandlerAdapter: TRACE
          filter:
            CommonsRequestLoggingFilter: TRACE
            GenericFilterBean: trace
          FilterChainProxy: trace

      apache:
        tomcat: info
    com:
      wjp:
        hellospring:
          log:
            Logger: info
trace: false

